spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  sql:
    init:
      platform: h2
      mode: always

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
       ddl-auto: none

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
