logging:
  level:
    org.springframework.security: trace

server:
  port: 8082

spring:
  config:
    import:
      - classpath:/db/mysql_db.yml
      - classpath:/application_oauth2_resource.yml

---

spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:/db/h2_db.yml
      - classpath:/application_oauth2_resource.yml
