logging:
  level:
    org.springframework.security: trace

server:
  port: 8082

spring:
  profiles:
    active: default
  config:
    import:
        - classpath:/application_oauth2_resource.yml
        - classpath:/db/mysql_db.yml

---

spring:
  profiles:
    active: test
  config:
    import:
      - classpath:/application_oauth2_resource.yml
      - classpath:/db/h2_db.yml

