package com.bos.resource.app.fota.model.constants.enums;

public enum OpCode {
    APPLICATION_LIST
    , DEVICE_INFO
    , DEVICE_LOCATION
    , DEVICE_LOCK
    , DEVICE_MUTE
    , DEVICE_RING
    , DEVICE_UNLOCK
    , ENTERPRISE_WIPE
    , FILE_DOWNLOAD_FROM_THE_DEVICE
    , FILE_UPLOAD_TO_THE_DEVICE
    , INSTALL_APPLICATION
    , MONITOR
    , NOTIFICATION
    , POLICY_BUNDLE
    , POLICY_REVOKE
    , REBOOT
    , REMOTE_CONNECT
    , UNINSTALL_APPLICATION
    , UPGRADE_FIRMWARE
    , WIPE_DATA
    , MCM_BUNDLE
    , MCM_REVOKE
}
